delimiters:
  begin: "<<< theme-switcher <<<"
  separator: "====="
  end: ">>> theme-switcher >>>"

commands:
  dark_to_light:
    - "gsettings set org.gnome.desktop.interface color-scheme 'prefer-light'"
    - "gsettings set org.gnome.desktop.interface cursor-theme 'custom'"
    - "pgrep kitty | xargs -I {} kill -SIGUSR1 {}"
    - "tmux source-file $XDG_CONFIG_HOME/tmux/tmux.conf"
  light_to_dark:
    - "gsettings set org.gnome.desktop.interface cursor-theme 'custom-white'"
    - "pgrep kitty | xargs -I {} kill -SIGUSR1 {}"
    - "tmux source-file $XDG_CONFIG_HOME/tmux/tmux.conf"

config_files:
  - name: "tmux"
    path: "$XDG_CONFIG_HOME/tmux/tmux.conf"
    comment_prefix: "#"
  - name: "kitty"
    path: "$XDG_CONFIG_HOME/kitty/kitty.conf"
    comment_prefix: "#"
  - name: "kitty-diff"
    path: "$XDG_CONFIG_HOME/kitty/diff.conf"
    comment_prefix: "#"
  - name: "bat"
    path: "$XDG_CONFIG_HOME/bat/config"
    comment_prefix: "#"
  - name: "vim"
    path: "$XDG_CONFIG_HOME/vim/vimrc"
    comment_prefix: "\""
  - name: "sioyek"
    path: "$XDG_CONFIG_HOME/sioyek/prefs_user.config"
    comment_prefix: "#"

extensions:
  - name: "search-light"
    settings:
      - path: "background-color"
        light: "(1.0, 1.0, 1.0, 1.0)"
        dark: "(0.0, 0.0, 0.0, 1.0)"
      - path: "border-color"
        light: "(0.73, 0.73, 0.73, 1.0)"
        dark: "(0.19, 0.19, 0.19, 1.0)"
  - name: "blur-my-shell"
    settings:
      - path: "panel/blur"
        light: "false"
        dark: "true"
  - name: "rounded-window-corners-reborn"
    settings:
      - path: "border-color"
        light: "(0.73, 0.73, 0.73, 1.0)"
        dark: "(0.18, 0.18, 0.18, 1.0)"
